### ISSUE TITLE
Draft feature architecture

### ISSUE THREAD

**Issue by crhx** [ChangeitlaterJACK/Soulgun#2]

**Comment by jcollums** [comment]
Initial sprites
- Circular image with color gradient for each entity type
- Maybe replaced with better sprites later

Map
- Fixed graphic (some walls maybe)
- Only a portion of map visible at any given time

Player sprite
- Keep track of where player is
- Player is centered on map
- Player can shoot in all directions

Enemy sprites
- Robotic and humanoid enemies
- Limit number of spawned enemies
- Enemies can move around player and shoot toward them
- Semi-random choices as to how to maneuver around player

Shots
- Shot projectiles continues until it hits or goes off-screen

Collision detection of projectile and player/enemies

Asteroids-like control scheme?
- W, S would move up or down, holding A or D would rotate player
- Clicking shoots

Alternate shot that possesses humanoid entities (shifting viewport to shot enemy's place)
- Maybe periodically more enemies surround player forcing them to possess humanoid enemy to escape it
- Transition to new map location could be smooth and gradual
- Alternate shots only collide with humanoid enemies

Pause/start
- Key to pause, or if window becomes unfocused

Timer or score counter
- To measure achievement

Rudimentary sound effects
- Maybe just sine-waves at different frequencies
